// Generated by CoffeeScript 1.8.0
var clientObject, clientToInterfaceAdapter, interfaceMethod;

clientObject = {
  string1: "foo",
  string2: "bar",
  string3: "baz"
};

interfaceMethod = function(str1, str2, str3) {};

clientToInterfaceAdapter = function(object) {
  return interfaceMethod(object.string1, object.string2, object.string3);
};

clientToInterfaceAdapter(clientObject);
