// Generated by CoffeeScript 1.8.0
var ATM, MoneyStack, atm;

MoneyStack = (function() {
  function MoneyStack(billSize) {
    this.billSize = billSize;
  }

  MoneyStack.prototype.withdraw = function(amount) {
    var numOfBills;
    numOfBills = Math.floor(amount / this.billSize);
    if (numOfBills > 0) {
      this._ejectMoney(numOfBills);
      amount -= this.billSize * numOfBills;
    }
    return amount > 0 && this.next && this.next.withdraw(amount);
  };

  MoneyStack.prototype.setNextStack = function(stack) {
    return this.next = stack;
  };

  MoneyStack.prototype._ejectMoney = function(numOfBills) {
    return console.log("" + numOfBills + " $" + this.billSize + " bill(s) has/have been spit out");
  };

  return MoneyStack;

})();

ATM = (function() {
  function ATM() {
    var stack1, stack10, stack100, stack20, stack5, stack50;
    stack100 = new MoneyStack(100);
    stack50 = new MoneyStack(50);
    stack20 = new MoneyStack(20);
    stack10 = new MoneyStack(10);
    stack5 = new MoneyStack(5);
    stack1 = new MoneyStack(1);
    stack100.setNextStack(stack50);
    stack50.setNextStack(stack20);
    stack20.setNextStack(stack10);
    stack10.setNextStack(stack5);
    stack5.setNextStack(stack1);
    this.moneyStack = stack100;
  }

  ATM.prototype.withdraw = function(amount) {
    return this.moneyStack.withdraw(amount);
  };

  return ATM;

})();

atm = new ATM;

atm.withdraw(186);

atm.withdraw(72);
