// Generated by CoffeeScript 1.8.0
var DynamicGallery;

DynamicGallery = (function() {
  function DynamicGallery(id) {
    this.childrens = [];
    this.element = document.createElement("div");
    this.element.id = id;
    this.element.className = "dynamic-gallery";
  }

  DynamicGallery.prototype.add = function(child) {
    this.children.push(child);
    return this.element.appendChild(child.getElement());
  };

  DynamicGallery.prototype.remove = function(child) {
    var children, _i, _len, _ref;
    _ref = this.childrens;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      children = _ref[_i];
      if (!(children === child)) {
        continue;
      }
      this.childrens.remove();
      break;
    }
    return this.element.removeChild(child.getElement());
  };

  DynamicGallery.prototype.getChild = function(n) {
    return this.childrens[n];
  };

  DynamicGallery.prototype.hide = function() {
    var children, _i, _len, _ref;
    _ref = this.childrens;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      children = _ref[_i];
      children.hide();
    }
    return this.element.style.display = "none";
  };

  DynamicGallery.prototype.show = function() {
    var children, _i, _len, _ref, _results;
    this.element.style.display = "block";
    _ref = this.childrens;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      children = _ref[_i];
      _results.push(children.show());
    }
    return _results;
  };

  DynamicGallery.prototype.getElement = function() {
    return this.element;
  };

  return DynamicGallery;

})();
