// Generated by CoffeeScript 1.8.0
var AppleNotebook, ImportNotebook, Notebook, NovaNotebook, macBookInRussia,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Notebook = (function() {
  function Notebook() {
    this.price = 500;
    this.hdd = 320;
    this.ram = 4;
    this.core = "i5 2.3";
  }

  return Notebook;

})();

NovaNotebook = (function(_super) {
  __extends(NovaNotebook, _super);

  function NovaNotebook(product) {
    NovaNotebook.__super__.constructor.call(this, product);
    this.price = this.product.price * 1.3;
  }

  return NovaNotebook;

})(Notebook);

ImportNotebook = (function(_super) {
  __extends(ImportNotebook, _super);

  function ImportNotebook(product) {
    this.product = product;
    this.price = this.product.price * 1.5;
  }

  return ImportNotebook;

})(Notebook);

AppleNotebook = (function(_super) {
  __extends(AppleNotebook, _super);

  function AppleNotebook(product) {
    AppleNotebook.__super__.constructor.call(this, product);
    this.price = this.price * 2.1;
  }

  return AppleNotebook;

})(Notebook);

macBookInRussia = new NovaNotebook(new Notebook);

console.log(macBookInRussia);
