// Generated by CoffeeScript 1.8.0
var DED, a, ab, addEvent, b, setCSS, setStyle,
  __hasProp = {}.hasOwnProperty;

addEvent = function(el, type, fn) {
  if (addEventListener) {
    return el.addEventListener(type, fn);
  } else if (attachEvent) {
    return el.attachEvent("on" + type, fn);
  } else {
    return el["on" + type] = fn;
  }
};

a = function(x) {};

b = function(y) {};

ab = function(x, y) {
  a(x);
  return b(y);
};

DED = DED || {};

DED.util = setStyle = function(elements, prop, val) {
  var element, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = elements.length; _i < _len; _i++) {
    element = elements[_i];
    _results.push(document.getElementById(element).style[prop] = val);
  }
  return _results;
};

setCSS = function(el, styles) {
  var prop, style, _results;
  _results = [];
  for (prop in styes) {
    if (!__hasProp.call(styes, prop)) continue;
    style = styes[prop];
    _results.push(setStyle(el, prop, style));
  }
  return _results;
};

DED.util.Event = {
  getEvent: function(e) {
    return e || event;
  },
  getTarget: function(e) {
    return e.target || e.srcElement;
  },
  stopPropagation: function(e) {
    if (e.stopPropagation) {
      return e.stopPropagation();
    } else {
      return e.cancelBuble = true;
    }
  },
  preventDefault: function(e) {
    if (e.preventDefault) {
      return e.preventDefault();
    } else {
      return e.returnValue = false;
    }
  },
  stopEvent: function(e) {
    this.stopPropagation(e);
    return this.preventDefault(e);
  }
};

addEvent(document.querySelector("body"), "click", function(e) {
  console.log(DED.util.Event.getTarget(e));
  return DED.util.Event.stopEvent(e);
});
